packages/snack-game/package.json
packages/snack-game/src/api/appleGame.ts
packages/snack-game/src/api/groups.ts
packages/snack-game/src/api/members.ts
packages/snack-game/src/components/games/AppleGame.tsx
packages/snack-game/src/components/ui/AuthForm/RegisterForm.tsx
packages/snack-game/src/components/ui/Header/Header.tsx
packages/snack-game/src/components/ui/SearchResultList/SearchResultList.tsx
packages/snack-game/src/constants/atom.constant.ts
packages/snack-game/src/constants/toast.constant.ts
packages/snack-game/src/hooks/queries/appleGame.query.ts
packages/snack-game/src/hooks/queries/groups.query.ts
packages/snack-game/src/hooks/queries/members.query.ts
packages/snack-game/src/hooks/useError.ts
packages/snack-game/src/hooks/useToast.ts
packages/snack-game/src/modules/snackRainManager.ts
packages/snack-game/src/utils/atoms/auth.ts
packages/snack-game/src/utils/types/member.type.ts
pnpm-lock.yaml

* 로그인
* 회원가입
* 그룹 서칭
* 관련 에러 핸들링
* auth 성공 메시지

feat: Auth 관련기능 완성

---

packages/snack-game/src/api/appleGame.ts
packages/snack-game/src/api/index.ts
packages/snack-game/src/components/games/AppleGame.tsx
packages/snack-game/src/components/games/AppleGameContainer.tsx
packages/snack-game/src/hooks/queries/appleGame.query.ts
packages/snack-game/src/modules/apple-game/apple.ts
packages/snack-game/src/modules/apple-game/appleGameManager.ts
packages/snack-game/src/utils/types/game.type.ts
packages/snack-game/src/utils/types/member.type.ts

* 시작
* 진행 
* 게임의 진행사항을 추적, 저장
* 종료 
* 추적중인 게임의 상태를 전송하여 채점 후 채점 성공시 세션을 정상 종료 요청

feat: 게임 라이프사이클 완성

---

packages/snack-game/src/game/view/gameModes/GoldMode.tsx

feat: 게임 종료 시 postMessage

---

.gitignore
src/api/apple-game.api.ts
src/api/auth.api.ts
src/api/index.ts
src/api/members.api.ts
src/components/Auth/OAuth.tsx
src/components/Header/Header.tsx
src/components/RouterLink/RouterLink.tsx
src/constants/localstorage.constant.ts
src/hooks/queries/appleGame.query.ts
src/hooks/queries/auth.query.ts
src/utils/types/member.type.ts

- 신규 피처
기존 localstorage에서 관리하는 accessToken이 cookie로 변경됨에 따라 기존 어플리케이션을 스팩에 맞게 수정했습니다.

Feat: accessToken localstorage -> cookie 로 저장소 변경

---

.gitignore
src/App.tsx
src/api/apple-game.api.ts
src/api/auth.api.ts
src/api/index.ts
src/api/members.api.ts
src/components/Auth/OAuth.tsx
src/components/Header/Header.tsx
src/components/RouterLink/RouterLink.tsx
src/constants/localStorage.constant.ts
src/constants/localstorage.constant.ts
src/hooks/queries/appleGame.query.ts
src/hooks/queries/auth.query.ts
src/utils/types/member.type.ts

- 신규 피처
토큰을 쿠키에서 관리하도록 수정 927387a005a9ba6442a8fab4bcfb9bfce895d9cd
유저 정보 만료기간 설정 및 토큰 재발급 로직 수정 ae91d28780f47fb8fda6c73174f06b5c9a435ea3

토큰 관련 변경사항 베포

---

src/api/index.ts
src/components/Footer/Footer.tsx
src/pages/games/AppleGame/AppleGamePage.tsx

- 신규 피처
- #143 
axios response intercepter 의 예외 처리를 수정했습니다. 6fa73651f1d5f2321372c97ec19b38a452a0fee0
```
axios response intercepter의 예외처리 보안
모든 에러의 action을 파싱해 처리를 하다보니 로그아웃이 필요하지 않은 작업에 로그아웃을 시키는 버그가 발생
ex) 중복된 이름으로 변경하는 경우 action이 null로 오다보니 logout이 수행됨.
따라서 오류의 상태코드에 따라 처리 하도록 변경
```
게임 페이지에 누락된 Footer를 추가했습니다. e0bfa29840c0c574886a0126c4947a2d07c7c486

Refactor:  axios

---

readme.md

git 테스트 커밋

---

src/api/auth.api.ts
src/utils/types/member.type.ts

- 리팩토링
- #171 
- #161 에서 말했던 이것
- `MemberType` 에서 사용하지 않는 속성 `guest` 삭제
밥먹우니까 졸려서 간단한 작업 먼저.. 했습니다.........

refactor: `MemberType` 관련 api 함수 리팩토링

---

src/pages/games/AppleGame/AppleGamePage.tsx
src/pages/games/AppleGame/game/model/snackGame/snack.ts
src/pages/games/AppleGame/game/model/snackGame/snackGameC.ts
src/pages/games/AppleGame/game/model/snackGame/snackGameD.ts
src/pages/games/AppleGame/game/view/snackGame/SnackGameModC.tsx
src/pages/games/AppleGame/game/view/snackGame/SnackGameModD.tsx

- 신규 피처
- #187 
B안의 조작방식 선택 객체의 3x3영역 내에서 선택 + 스낵 제거 시 새로운 스낵 생성
A안의 룰 + B안의 선택 객체의 가장 가까운 모든 객체 선택가능

feat: 새로운 게임모드 C안 D안 추가

---

.github/workflows/develop-build-test.yml

- 이슈 대응
- #237 에서 액션 에러가 나는데,
빌드 단계에서 터진 게 아니더라고용.. 따끈따끈한 관련 이슈가 있길래 링크 달아두겠습니다
➡️➡️➡️ https://github.com/pnpm/action-setup/issues/135
- action/setup@v2 -> action/setup@v4

fix: develop-build-test.yml의 action-setup 버전 수정

---

src/api/index.ts

- 리팩토링
- #239 
서버 예외처리 방식에 맞게 action을 삭제하고 code로 수정했습니다 
인터셉터에서 쓰는 code가 1개 밖에 없어서 일단 기존 방식처럼 하드코딩 해놨어욥
7/8 코어타임에 action 삭제 예정이랬어서........ 벼락치기로다가....
첫 출근 아자아자! 화이팅! 입니다

refactor: axios 인터셉터 내 `action` 삭제 후 `code`로 교체

---

src/pages/games/SnackGame/game/screen/GameScreen.ts

feat(SnackGame): 게임 시간을 120초로 한다

---

index.html

- 이슈 대응
- resolves: https://github.com/snack-game/front/issues/252
- 저렇게 추가해두면 http 요청을 https로 업그레이드 해서 보내준다네용
- [07/15 회의록](https://www.notion.so/07-15-11-00-672038b0a7a4459daab5b11ca3fcf854)에도 관련 내용이 있습니다
- WebView에서 확인해보고 안되면 다른 방법으로 PR 올릴 예정이라 어푸룹 없이 머지 한번 해보겠습니다!!!!!!!!

fix: index.html에 CSP 설정용 meta 태그 추가

---

src/api/index.ts

별건 아니구 서버에서 아래 변경사항 만들면서 생각난 김에 함께 리팩터링합니다.
- https://github.com/snack-game/server/pull/156
👆🏻 요거 머지할 때 이 PR도 함께 머지하겠습니다.
`REFRESH_TOKEN_EXPIRED_EXCEPTION`을 정의해서 해당 코드를 명시했습니다.
또 불필요하게 depth가 깊은 switch 문을 걷어냈습니다.

refactor(api): 리프레시 토큰 만료 예외를 명시한다

---

pnpm-lock.yaml
src/App.tsx
src/api/apple-game.api.ts
src/api/auth.api.ts
src/api/groups.api.ts
src/api/history.api.ts
src/api/index.ts
src/api/members.api.ts
src/api/ranking.api.ts
src/components/Header/Header.tsx
src/hooks/queries/appleGame.query.ts
src/hooks/queries/auth.query.ts
src/hooks/queries/groups.query.ts
src/hooks/queries/history.query.ts
src/hooks/queries/members.query.ts
src/hooks/queries/ranking.query.ts
src/pages/GameLayout.tsx
src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
src/pages/user/components/GuestToMember.tsx
src/pages/user/setting/SettingPage.tsx

- 신규 피처
- #277 
기존 API들은 다음과 같이 객체로 관리를 해왔다.
```typescript
const appleGameApi = {
endPoint: {
game: '/v2/games/1',
checkMove: '/v2/sessions',
gameEnd: '/v2/sessions',
gameRefresh: '/v2/sessions',
},
gameStart: async (): Promise<goldModeType> => {
const { data } = await api.post(appleGameApi.endPoint.game);
return {
apples: data.apples,
sessionId: data.sessionId,
score: data.score,
};
},
```
집약적으로 관리가 가능하다는 장점과 사용하는 입장에서도 하나의 객체만 참고하면 되는 장점이 있었지만,
다음과 같은 문제가 있었다.
```typescript
const rankingApi = {
endPoint: {
ranking: ({
gameId,
season,
user = false,
}: {
gameId: RankingViewType;
season?: number;
user?: boolean;
}) => {
const seasonPath = season ? `/${season}` : '';
const userPath = user ? '/me' : '';
return `/rankings/${gameId}${seasonPath}${userPath}?by=BEST_SCORE`;
},
seasons: …
```

refactor:api to function

---

public/locale/en/setting.json
public/locale/en/withdraw.json
public/locale/ko/setting.json
public/locale/ko/withdraw.json
src/App.tsx
src/api/auth.api.ts
src/constants/path.constant.ts
src/hooks/queries/members.query.ts
src/pages/user/setting/SettingPage.tsx
src/pages/withdraw/WithdrawPage.tsx

- 신규 피처
- #279
회원 탈퇴 페이지를 구현했습니다
이거 하면서 닉네임 랜덤 생성도 직접 확인해볼 수 있었네요 시나브로 쓸쓸한 스낵이가 저였답니다 짜잔~
아!!!!!!!!!!!!!! 토스트 말고 화면에 있는 텍스트도 번역 가능하게 해둘게요 깜빡했다!!!!!!!!!!!!!!!

feat: 회원탈퇴 기능 구현

---

public/locale/en/translation.json
public/locale/ko/translation.json
src/hooks/queries/auth.query.ts
src/pages/games/SnackGame/game/SnackGameBase.tsx
src/pages/games/SnackGame/game/screen/LobbyScreen.ts

- 이슈 대응 겸 신규 피처
- #283 
- 로그인 하지 않은 상태에서 `기본 모드`를 누르면 자동으로 게스트 로그인을 수행합니다!
- 시점: `로비 스크린` -(이때 수행됩니다)-> `게임 스크린`
|before|after|
|:---:|:---:|
|![game](https://github.com/user-attachments/assets/8c10fa36-db66-4ccb-90df-fea76940425e)|![guest_login](https://github.com/user-attachments/assets/2aeceab2-231a-49a5-a65d-40657327e3db)|

fix: 비로그인 상태에서 게임 시작하면 가만히 멈춰있는 문제

---

src/pages/games/SnackGame/game/SnackGameBase.tsx
src/pages/games/SnackGame/game/popup/PausePopup.ts

- 신규 피처
그만두기 버튼은 작게, 재개 버튼은 크게 만들었어요
더 좋은 아이디어가 있으면 추후 수정 부탁드립니다 👀

feat(PausePopup): 게임을 그만둘 수  있다

---

src/pages/games/SnackGame/game/screen/LobbyScreen.ts
src/pages/games/SnackgameBiz/SnackGameBizBase.tsx

안녕하세용 하루만에 또 PR 올립니다 :)
스낵게임Biz에 재시작 구현을 안해뒀더라구요
지금 구현해서 배포합니다!
관련한 문서는 [여기](https://blog.snackga.me/snackgame-biz#block-14400ca278ab802991ccd2d49db258cf)에서 확인할 수 있습니다
스낵게임 Biz 클라이언트 측의 게임 재시작 요청을 수신할 수 있습니다.

feat(SnackgameBiz): 클라이언트가 직접 게임을 재시작할 수 있다

---

global.d.ts
src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
src/pages/games/SnackGame/game/screen/GameScreen.ts
src/pages/games/SnackGame/game/snackGame/SnackGameAction.ts
src/pages/games/SnackGame/game/util/hapticFeedback.ts
src/pages/games/SnackgameBiz/SnackGameBizBase.tsx
tsconfig.json

- resolves: #327 
스낵게임에 햅틱 피드백을 적용합니다
관련 문서는 [요기](https://www.notion.so/15100ca278ab8021b690dd9f9fc0b312?pvs=4)!
테스트는 TestFlight에서!
(특정 브랜치를 개발서버에 올릴 수 있도록 [github actions workflow](https://github.com/snack-game/front/actions/workflows/ci-development.yml)에 [`workflow_dispatch` 추가했습니다](https://github.com/snack-game/front/commit/fda7dc7f55d20f3d40733eb5f11a1f10d0e745af))
브랜치 선택 -> run workflow
- 게임 클라이언트에 햅틱 피드백 호출 추가
- 이벤트 기반 인터페이스를 사용합니다
이거 하다보니.. 게임 로직이 여기저기 흩어져있어서 (응집도 ⬇️) 햅틱 호출을 어디에 넣을지 찾아다니느라 혼났습니다
스낵게임 코어부분 코드가 리팩터링이 시급한 상태인 것 같아요..!
다음 이터레이션에서 정리 한번 시작해보겠습니다

feat: 스낵게임 햅틱 피드백 적용

---

src/constants/path.constant.ts
src/pages/games/SnackGame/game/legacy/components/GameResult.tsx

- 리팩토링
- 게임 안에 있던 이벤트 폼 이동 버튼 / 상수를 지웠어요
- 왜냐면 오늘 밤에 이벤트 끝나니까................

remove: GameResult 내 이벤트 참여 버튼 삭제

---

public/locale/en/game.json
public/locale/ko/game.json
src/components/Modal/Modal.tsx
src/hooks/queries/provocation.query.ts
src/hooks/useModal.ts
src/pages/PrivateRoute.tsx
src/pages/games/SnackGame/game/SnackGameBase.tsx
src/pages/games/SnackGame/game/components/ProvocationSender.tsx
src/pages/games/SnackGame/game/util/provocation.api.ts
src/utils/types/common.type.ts

- 신규 피처
- #326 
- 최고 기록 갱신 시 이용 가능한 도발 기능을 추가했습니다
- 모바일 앱 && 로그인한 사용자일 때 이용 가능합니다!!!
||전송 성공|전송 실패|
|---|---|---|
||![image](https://github.com/user-attachments/assets/de7a8c69-c50f-479c-8caa-940f148e1965)|![image](https://github.com/user-attachments/assets/f9f67a72-8edc-4808-a617-9647436c6e81)|
|받는 사람|![image](https://github.com/user-attachments/assets/8ec3b6bc-b077-4a3d-9e98-294d151bd453)||

feat: 도발 기능 추가

---

src/api/item.api.ts
src/pages/games/SnackGame/game/hook/useNoticeModal.tsx
src/pages/games/SnackGame/game/screen/GameScreen.ts
src/pages/user/components/DailyRewardBox.tsx
src/pages/user/components/ItemSection.tsx

- 신규 피처
- #366 
- `<Notice>`에 폭탄 공지를 작성했습니다
- 아직 피버타임이...... 덜 된 관계로 게임과 마이페이지에서 숨겼습니다 피버야 미안하다아아악
- 일일 보상 API의 요청 바디를 수정했습니다
- `grant: DAILY` 필드를 추가했십니더

feat: 폭탄 아이템 기능 추가 공지 작성

---

src/pages/games/SnackGame/game/SnackGameBase.tsx
src/pages/games/SnackGame/game/screen/GameScreen.ts
src/pages/games/SnackGame/game/snackGame/SnackGame.ts
src/pages/games/SnackGame/game/snackGame/SnackGameBoard.ts

- 이슈대응
- #371 
- 이슈 캡쳐로 대신하겠읍니다

fix: 폭탄 사용 시 스트릭 검증 추가

---

src/pages/games/SnackGame/game/SnackGameBase.tsx
src/pages/games/SnackGame/game/ui/ItemBar.ts

- 이슈대응
- #373 
- 자동 게스트 로그인할 때 게임 시작이 안 되는 버그를 수정했습니다
| before | after |
|:---:|:---:|
|![error](https://github.com/user-attachments/assets/fa94e19a-6305-46a3-bc0e-1fc39719c239)|![after](https://github.com/user-attachments/assets/1cf41853-dac8-43f2-8aea-6586e6c3c65c)|

fix: 게스트 모드에서 게임 시작이 안되는 버그

---

src/pages/games/SnackGame/game/screen/GameScreen.ts
src/pages/games/SnackGame/game/ui/ItemBar.ts
src/pages/games/SnackGame/game/ui/ItemButton.ts

- 신규 피처
- #377 
- 아이템 사용 중에는 다른 아이템을 사용할 수 없게 비활성화합니다

feat: 아이템 사용 중 중복 사용 방지 기능 추가
