snack-game/front

- packages/snack-game/src/api/auth.api.ts
- packages/snack-game/src/api/members.api.ts
- packages/snack-game/src/components/ui/AuthForm/LoginForm.tsx
- packages/snack-game/src/components/ui/AuthForm/OAuthHandler.tsx
- packages/snack-game/src/components/ui/AuthForm/RegisterForm.tsx
- packages/snack-game/src/components/ui/GameResult/GameResult.tsx
- packages/snack-game/src/components/ui/Header/Header.tsx
- packages/snack-game/src/components/ui/RankingTable/RankingTable.tsx
- packages/snack-game/src/components/ui/UserInfo/UserInfo.tsx
- packages/snack-game/src/hooks/game/useAppleGameController.tsx
- packages/snack-game/src/hooks/queries/appleGame.query.ts
- packages/snack-game/src/hooks/queries/auth.query.ts
- packages/snack-game/src/hooks/queries/members.query.ts
- packages/snack-game/src/pages/ranking/RankingPage.tsx
- packages/snack-game/src/utils/atoms/member.atom.ts
- packages/snack-game/src/utils/types/member.type.ts
```typescript
export interface MemberType {
id?: number;
name?: string;
group: GroupType | null;
guest?: boolean;
accessToken?: string;
}
export interface AuthType {
member: MemberType;
accessToken: string;
}
```
* 불필요하게 나누어진 MemberType을 통합
```typescript
export type AuthType = 'SOCIAL' | 'GUEST' | 'SELF';
export interface MemberType {
member: {
id?: number;
name?: string;
group: GroupType | null;
guest?: boolean;
type?: AuthType;
};
accessToken?: string;
}
```
* 서비스 요구사항 변경에 따른 계정 타입 정보 추가 AuthType
> feat: Member 타입 수정

- src/assets/icon/hamburger.svg
- src/components/Header/Header.tsx
- src/components/Loading/Loading.stories.tsx
- src/components/Spacing/Spacing.tsx
- src/pages/games/AppleGame/components/AppleGameHeader.tsx
- 신규 피처
- #114 
헤더를 반응형으로 수정했습니다.
컴포넌트 컴파운딩패턴으로 아래와 같이 페이지에 따라 Header에 Nav 요소를 추가할 수 있습니다.
```tsx
<Header>
<Header.ListItem>
<RouterLink
to={PATH.APPLE_GAME}
className={'items-center'}
isActivated={location == PATH.APPLE_GAME}
>
<GameIcon className={'mr-4 h-6 w-6'} />
<span>게임</span>
</RouterLink>
</Header.ListItem>
<RouterLink
to={PATH.APPLE_GAME_RANKING}
className={'items-center'}
isActivated={location == PATH.APPLE_GAME_RANKING}
>
<RankingIcon className={'mr-4 h-6 w-6'} />
<span>랭킹</span>
</RouterLink>
</Header>
```
이것저것 하다보니 헤더 컴포넌트가 복잡해졌네요..ㅎ
아직은 헤더가 텅텅 비어보이기도 하고 그러네요.
추후에 레벨, 개인 프로필 등 고도화 작업이 이루어지면 아래 사이트처럼 바꾸는것도 좋은것 같은데 어떻게 생각하시나요?
https://solved.ac/
> feat: header 반응형으로 수정

- src/components/Carousel/Carousel.tsx
- src/pages/main/components/HeroSection.tsx
- UI 리팩토링
- #115 
이미지가 일부 잘리거나, 컴포넌트 간 영역 침범으로 컨텐츠가 겹치는 현상을 고쳤습니다~!
(왼쪽: 고친 후 / 오른쪽: 현재 배포판)
1. 캐러셀 내 사과 이미지 약간! 잘리던 현상
2. 화면 확대 시 HeroSection이 Spacing을 침범하던 현상
> refactor: 랜딩 페이지 UI 수정

- src/App.style.tsx
- tailwind.config.js
- 신규 피처
- #117 
- `tailwind.config.js` - `dovemayo`를 `sans`로 변경했습니다
(참고: [tailwind Font Family](https://tailwindcss.com/docs/font-family)의 **Customizing the default font** 문단)
- `App.style.tsx` - `globalStyles` 내 font-family 설정을 제거했습니다
|적용 전|적용 후|
|---|---|
|![image](https://github.com/snack-game/front/assets/87255462/5e8616e6-df70-4993-b322-bb5f429c7e41)|![image](https://github.com/snack-game/front/assets/87255462/786a8305-81dd-4855-8fc6-637b28216e22)|
> feat: 못생긴 폰트 바꾸기

- src/pages/main/components/HeroSection.tsx
- 리팩토링
- #123 
- 가로 길이가 세로보다 더 긴 landscape 모드일 때만 `min-h-screen`을 적용합니다.
|이전|이후|
|---|---|
|![image](https://github.com/snack-game/front/assets/87255462/fcc39243-acc8-43f4-b154-08650dcbb752)|![image](https://github.com/snack-game/front/assets/87255462/ab2274d4-230c-4e70-b54d-2beedf8b2277)|
> refactor: 가로 모드일 때만 min-h-screen 적용

- src/App.tsx
- src/api/index.ts
- src/components/Auth/OAuth.tsx
- src/components/Header/Header.tsx
- src/constants/localStorage.constant.ts
- src/hooks/queries/auth.query.ts
- 신규 피처
- #131 
로그인 수행시 현재 시간을 기준으로 시간을 localstorage에 기록합니다.
해당 유저 로그인 시간은 토큰 재발급 시에 refreshToken과 함께 갱신이 됩니다.
App 에서는 최초 접속 시 유저 만료기한을 체크하고 현재 시간과 유저의 로그인 시간 정보가 1달 이상 차이가 난다면 토큰들은 모두 만료된것으로 판단, 유저 정보를 지우고 localstorage의 값도 마찬가지로 삭제합니다.
> refactor: 토큰 관리 수정, 유저 만료기간 설정

- src/components/Header/Header.tsx
- src/components/Hero/Hero.tsx
- 이슈대응
- #132 
- 항상 랜딩 페이지 내 `HeroSection`의 양쪽 여백을 보장하기 위해 space-between ➡ space-around로 수정했습니다
- 특정 상황에서 `Header`의 여백이 과하게 생기는 문제를 해결했습니다
> Fix: 랜딩 페이지, 헤더 UI 버그 수정

- .eslintrc.json
- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/components/base/QueryBoundary.tsx
- src/hooks/queries/appleGame.query.ts
- src/hooks/queries/auth.query.ts
- src/hooks/queries/groups.query.ts
- src/hooks/queries/members.query.ts
- src/hooks/queries/ranking.query.ts
- src/main.tsx
- src/pages/user/components/ProfileSection.tsx
- 리펙토링
- #157 
react query 라이브러리의 버전을 v3 -> v5로 업데이트 했습니다.
react query v5의 주요 변경사항은 아래 공식문서에서 확인가능합니다!
[주요 변경사항 참고 공식문서](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5)
* useErrorboundary 옵션의 이름이 변경되었습니다: throwOnError
* query key의 경우 옵션 필드에 queryKey로 명시해주어야 합니다.
* 기존 string으로 넣어주던 key는 배열로 변경되었습니다.
* [v4 공식문서](https://tanstack.com/query/v4/docs/framework/react/guides/migrating-to-react-query-4)
```
- useQuery('todos', fetchTodos)
+ useQuery(['todos'], fetchTodos)
```
* suspens: true나 throwOnError: true를 켜줄필요 없는 useSuspenQuery가 추가되었습니다.
> refactor: react query 버전업

- src/pages/user/components/ExpChart.tsx
- src/utils/types/member.type.ts
- 이슈 대응
- #159
- 경험치 관련 `StatusType`의 속성명을 서버 스키마랑 동일하게 살짝. 수정했어요
실행 화면이 달라진 건 없어서 사진은 첨부하지 않았습니다~!
> fix: `StatusType`의 `maximumExp` -> `maxExp`

- src/api/auth.api.ts
- src/api/members.api.ts
- src/components/Auth/OAuth.tsx
- src/components/Header/Header.tsx
- src/hooks/queries/appleGame.query.ts
- src/hooks/queries/auth.query.ts
- src/pages/games/AppleGame/components/GameResult.tsx
- src/pages/games/AppleGame/components/RankingSection.tsx
- src/pages/user/components/ProfileSection.tsx
- src/utils/atoms/member.atom.ts
- src/utils/types/member.type.ts
- 리팩토링
- #154 
- `MemberType`에서 `member`로 한번 묶는 부분을 삭제했습니다. 
- 서버와 동시에 타입 수정을 하는 게 아니라서 임시로 api 함수의 return문에 삼항 연산자가 들어갔는데요?
이 부분은 서버 수정이 끝나면 `return data;`만 남길 예정입니다
- `MemberType`에 `status` 속성을 추가했습니다
- 이제 `MemberProfileType`은 `MemberType`과 동일하기 때문에 멸종시켰습니다 
속성이 필수냐 vs 선택이냐 하는 차이가 있긴 했지만!
프로필은 data가 defined인 게 보장되는 `useSuspenseQuery`로 가져오기 때문에 `MemberType`을 써도 괜찮다고 생각했어욥
> refactor: `MemberType` member 속성 제거, `MemberProfileType` 삭제

- src/api/groups.api.ts
- src/api/members.api.ts
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- src/hooks/useInput.ts
- src/pages/user/components/EditImage.tsx
- src/pages/user/components/EditInfo.tsx
- src/pages/user/components/ProfileSection.tsx
- src/pages/user/components/UserInfo.tsx
- 리팩토링
- #163 
- `ProfileSection`에서 profileImage 편집 / name, group 편집에 대한 부분을 user 폴더 하위 컴포넌트로 분리했습니다
- name, group 편집 컴포넌트 `EditInfo`에서 useInput 훅의 리턴 값을 **객체로 받아서** 사용합니다
newName, nameValid, .. 이런 식으로 하나하나 받으려면 인자가 너무 많아져서 이렇게 해봤어요!!
그런고로,, useInput의 리턴 타입을 정의해서 사용했습니다
- name, group 편집에 사용되는 `Input` 컴포넌트를 common 폴더 하위 컴포넌트로 분리했습니다
- 원래 `ProfileSection`을 조회 / 편집 두 종류의 컴포넌트로 쪼개려다가 편집 컴포넌트 분리하고 나니까
조회는 굳이 분리 안 해도 될 크기라서 고냥 `ProfileSection` 안에 냅뒀습니다......!!
<details>
<summary> profileImage 관련 논의 </summary>
- 로컬 스토리지 `profileImage`는 업데이트 되지 않는데 괜찮을까요 이거
프로필 이미지 업데이트 시 s3 버킷 주소가 응답으로 오진 않음
➡ 프로필 수정해도 localStorage에 이전 프로필 이미지 주소가 남아있음
(업데이트 완료하면 서버에 요청을 한번 더 보내니까 바뀐 정보가 바로 보이지만)
🤔 지금은 로컬 스토리지에 있는 `profileImage`를 쓰는 곳이 없어서 문제가 없긴 합니다
- 근데 랭킹에서 이미지를 쓰게 된다면?!?!?! 
RankOwnerResponse에 `profileImage` …
> refactor: `ProfileSection` 컴포넌트를 분리

- .storybook/preview.tsx
- src/api/ranking.api.ts
- src/assets/icon/down-arrow.svg
- src/components/DropDown/DropDown.stories.tsx
- src/components/DropDown/DropDown.tsx
- src/components/Level/Level.stories.tsx
- src/components/Level/Level.tsx
- src/constants/api.constant.ts
- src/hooks/queries/ranking.query.ts
- src/pages/games/AppleGame/RankingPage.tsx
- src/pages/games/AppleGame/components/OtherRanking.tsx
- src/pages/games/AppleGame/components/RankingSection.tsx
- src/pages/games/AppleGame/components/TopRanking.tsx
- src/pages/games/AppleGame/components/UserRanking.tsx
- src/utils/types/common.type.ts
- 신규 피처
- #166 
- #151 
11ca464dade75ad462a028ac9dd3e1ce6a9e8f61
level을 표시하기 위해 ranking 페이지용 level 컴포넌트와 
dropdown 컴포넌트가 추가되었습니다. 
기존 RankingType의 중복 영역을 대체했습니다.
```tsx
export type RankingType = {
rank: number;
owner: {
id: number;
name: string;
group: GroupType | null;
};
score: number;
message?: string;
};
to
owner: MemberType;
```
DropDown 컴포넌트는 
DropDownOptionType[]을 전달받아 name을 option에 렌더링 합니다. 초기에 보여줄 컨텐츠를 initalOption Prop을 전달이 가능하고 따로 설정하지 않으면 옵션중 첫 번째 값 [0]이 선택됩니다.
```tsx
export type DropDownOptionType = {
name: string;
onClick: () => void;
value?: string | number;
};
```
DropDownOptionType에 명시된 대로 각 option이 선택되었을 때 수행할 로직을 onClick을 통해 전달하고 DropDown컴포넌트는 사용자가 option 선택 시 해당 handleClickOption함수에서 자신의 상태를 변경하고 전달 받은 로직을 수행합니다.
ccb430426014368c88d2e24bdabe7d39961b0c67
> feat: 랭킹 페이지 사용자 level 표시, 시즌제 도입

- .github/workflows/ci-development.yml
- src/main.tsx
- src/pages/games/AppleGame/components/RankingSection.tsx
- 이슈대응
- #174 
프론트 개발버전 베포  환경에서 ga tag id를 로딩하려고 하여 환경변수가 없으면 로딩하지 않도록 했습니다.
ranking page에서 user ranking의 분기문을 user id가 존재 여부에 따라 렌더링 여부를 결정했는데 게스트 유저도 user id가 존재하기 때문에 user ranking api 요청시 401 오류가 발생하는 부분을 수정했습니다.
5c6da33412893fdd97aaa2ea5ae4efd54b37dfd7
git을 연결해두면 거의 모든 활동에 preview 베포를 진행하기 때문에 불필요한 베포를 제거하고 효율적으로 수행하기 위해 vercel과 레포지토리 연동을 끊고 action에서 베포합니다.
9ce74db365d04c3963566006ff7815f9f72fc495
> fix: 개발환경 ga 제거, rankingpage user ranking 분기문 수정

- src/components/Auth/OAuth.tsx
- src/constants/path.constant.ts
- src/pages/games/AppleGame/components/RankingSection.tsx
- 이슈 대응
- #177 
baseURL 기준으로 API요청을 보내지 않고 하드코딩 되어있던 url 때문에 개발 버전에서 프로덕션 환경 서버로 요청을 보내는 이슈가 있었습니다.
해당 URL 부분을 제거하고 oAuth 요청 url을 다음과 같이 동적으로 적용할 수 있도록 변경했습니다.
```typescript
const oAuthURL = import.meta.env.VITE_API_URL + url;
```
> fix: path.constant 하드코딩된 url 제거 base url기준으로 oauth 요청

- src/pages/user/components/EditInfo.tsx
- src/pages/user/components/ProfileSection.tsx
- 리팩토링
- #176 
- `useGetGroupsNames` 훅을 `EditInfo` 내로 이동시켰습니다.
- 따라서 해당 훅에서 사용하는 값과 관련된 `useDebounce`도 같이 이사했습니다
- `EditInfo` 컴포넌트의 불필요한 props를 제거했습니다
|이전|현재|
|:---:|:---:|
|![image](https://github.com/snack-game/front/assets/87255462/5e800749-c896-4a63-a90d-b8304b42b0c1)|![name](https://github.com/snack-game/front/assets/87255462/6be434f1-681a-4935-943a-95b0839850b2)|
|프로필 수정 전에도 검색 쿼리 날아가는 중|수정 버튼 눌러야 날아감|
서버 요청은 필요할 때만!!! 하면 되는데 컴포넌트 분리할 때 이 부분에 대한 고민이 부족했던 거 같아요 🤔
좋은 지적 감사감사합니다!!!!!!!!!!!!!
> refactor: `useGetGroupsNames` `useDebounce`를 `EditInfo` 컴포넌트로 이동

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/api/apple-game.api.ts
- src/components/Modal/Modal.tsx
- src/pages/games/AppleGame/components/ExpBarChart.tsx
- src/pages/games/AppleGame/components/GameResult.tsx
- src/pages/games/AppleGame/game/game.type.ts
- src/pages/games/AppleGame/game/view/appleGame/DefaultMode.tsx
- 신규 피처
- #153
- 게임 종료시 모달(`GameResult`)에서 레벨/경험치 정보를 그래프로 보여줍니다.
- 게스트가 아닌 회원에게만 노출되는 UI입니다
- 화면 너비가 좁고 && 경험치가 낮을 때는 퍼센트 텍스트가 일부 잘리는 현상이 있어 경험치에 따라 텍스트 위치를 다르게 지정해놨습니다
| 40% 미만 | 40% 이상 |
|:---:|:---:|
| <img width="420" alt="anchor_end" src="https://github.com/snack-game/front/assets/87255462/af4ea55a-17aa-4f3a-81d6-d5c7bbfa9637">|<img width="422" alt="anchor_center" src="https://github.com/snack-game/front/assets/87255462/0301c503-fc3e-42a7-b230-a3be61dc4840">|
1. 원래 이 부분에서 API 호출이 2번 있어서 (게임 세션 종료, 프로필 정보)
지연 시간 동안 로딩 UI를 띄워서 처리해보기로 회의때 얘기가 됐었는데요!!
로딩 UI가 없어도 크게 문제되는 부분이 없어서 일단 그 부분은 제외하고 올렸습니다
2. `GameResult` 내부 내용들 (점수, 레벨, 경험치, 상위 %) 사이 위계 구분이 잘 안되는 거 같아 글자 스타일에 변화를 좀 줘보려고 합니다!! 이 부분은,, 피그마 슬쩍 만져보고 이따 코어 타임에 슬쩍 공유해볼게요
> feat: 게임 종료 모달에 레벨/경험치 정보 추가

- src/pages/user/components/ExpChart.tsx
- 이슈대응
- #182 
- `ExpChart` 도넛 차트에서 데이터 라벨이 보이지 않도록 display: false를 지정해줬습니다
흠.................... 차트 많이 썼으면 매번 display:false 지정하기 좀... 번거로웠을 거 같으네요
지금은 차트 2개만 있으니까 일단 봐주지만....
|display 지정 전 (default true)|display 지정 후|
|:---:|:---:|
|![image](https://github.com/snack-game/front/assets/87255462/f410bff0-c5f5-42ea-a447-e6536988e374)|![image](https://github.com/snack-game/front/assets/87255462/f8d1c54f-c0d2-49a5-9db6-cb66b5297b99)|
> fix: `ExpChart` 내 도넛 차트의 datalabels display:false로 지정

- package.json
- pnpm-lock.yaml
- src/components/Button/Button.tsx
- src/components/Header/Header.tsx
- src/components/RouterLink/RouterLink.tsx
- src/pages/user/components/EditInfo.tsx
- 이슈 대응
- #138 
- props로 className을 받는 공통 컴포넌트에 `twMerge`를 사용하도록 수정했습니다.
(이제 확인 버튼 초록색으로 잘 뜸)
`RouterLink`의 기본 style이 꽤 복잡해서, `defaultStyle`이라는 변수로 뺐는데 이럴거면 아예 하나하나 다 쪼개는 게 나을까요?
```ts
// 현재
const defaultStyle = `flex font-medium underline-offset-4 transition-colors duration-200 ${
hover &&
'hover:border-b-2 hover:border-b-primary hover:font-bold hover:text-primary'
} ${isActivated ? 'text-primary' : 'text-gray-400'}
`;
// 조각조각 땃땃따
const defaultStyle = `flex font-medium underline-offset-4 transition-colors duration-200`
const hoverStyle = `${hover && 'hover:border-b-2 hover:border-b-primary hover:font-bold hover:text-primary'}`
const textStyle = `${isActivated ? 'text-primary' : 'text-gray-400'}`;
```
> fix: tailwind css className 병합 문제를 tailwind-merge로 해결

- src/api/ranking.api.ts
- src/constants/api.constant.ts
- src/hooks/queries/ranking.query.ts
- src/pages/games/SnackGame/ranking/RankingPage.tsx
- src/pages/games/SnackGame/ranking/components/UserRanking.tsx
- src/utils/types/common.type.ts
- 리팩토링
- #202 
- 시즌 정보를 서버에서 받아와서 띄우는 방식으로 수정했습니다
- 진행 중인 시즌은 endedAt 필드가 null이어서 `SeasonType.endedAt: string | null` 입니다!
- 시즌 정보는 매번 새로 받아올 필요가 없다고 생각해서 (자주 안 바뀌니까) staleTime을 30일로 넣어봤습니다
- `UserRanking` bottom 값을 수정했습니다
- `BottomNav`랑 겹쳐서 보이고 있어서 살짝 올렸어요!!
> Feat: 시즌 정보를 서버에서 받아오기

- package.json
- pnpm-lock.yaml
- src/App.tsx
- src/components/Level/Level.tsx
- src/components/base/ErrorBoundary.tsx
- src/constants/common.constant.ts
- src/constants/toast.constant.ts
- src/hooks/useToast.ts
- src/main.tsx
- src/pages/games/SnackGame/game/components/ExpBarChart.tsx
- src/pages/games/SnackGame/game/view/snackGame/SnackGameView.tsx
- src/pages/user/components/ExpChart.tsx
- src/utils/atoms/common.atom.ts
- 신규 피처
- #205 
6fd324c4130f6ff897ebba1eadb96f611f760bf2
main.tsx 에서 초기화 됩니다. Hotjar와 GA는 production 에서만 데이터를 수집하는게 맞다고 생각해 Sentry와는 구분했습니다.
Hotjar에 필요한 HJID, HJSV 는 딱히 숨길 필요가 없어 constants 파일에 정의했습니다.
```tsx
if (import.meta.env.VITE_NODE_ENV === 'production') {
ReactGA.initialize(import.meta.env.VITE_GA_TRACKING_ID);
hotjar.initialize({ id: HJID, sv: HJSV });
}
```
3fd7bbaa3730c5562c9d0e6cf5179067d8112927
마찬가지로 main.tsx에서 초기화 됩니다.  개발버전(staging) 에서 QA를 진행하기에 개발버전의 오류도 수집할 수 있도록 따로 분리해 초기화했습니다.
개발환경 development 에서는 Sentry가 초기화되지 않습니다.
에러 모니터링, API 퍼포먼스 모니터링, 세션 리플레이 기능이 켜져 있는 설정입니다.
```tsx
Sentry.init({
dsn: import.meta.env.VITE_SENTRY_DNS,
integrations: [
Sentry.browserTracingIntegration(),
Sentry.replayIntegration(),
],
// Performance Monitoring
tracesSampleRate: 1.0, …
```
> Feat: Hotjar, Sentry 설치 및 초기 설정

- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameBoard.ts
- src/pages/games/SnackGame/game/ui/GameEffect.ts
- src/pages/games/SnackGame/game/ui/PopExplosion.ts
- src/pages/games/SnackGame/game/ui/Score.ts
- src/pages/games/SnackGame/game/ui/Timer.ts
- 신규 피처
- #219 
- #217 
> 점수통에 시간이 들어있어서 왜 차는건지 이해하기 어려움 또, 점수통이 꽉차는 기준이 없어서 얼마나 깨야 점수통이 차는건지 이해하기 어려움
이런 문제가 있어서 좀 더 UI요소의 역할을 명확히 하고자 위치 및 애니메이션을 교체했습니다.
이에 따라 스낵이 날아가는 위치도 변경되었습니다.
현재 화면 높이가 부족한 경우 footer에 SnackGameBoard가 가려지는 문제가 있는데요.
높이에 따라 tilesize를 반응형으로 설정을 해봤었는데요 (기존 50에서 높이에 따라 최하 45까지) 
이런 경우에 생각보다 너무 작아서 불편함이 있더라구요 
사실 footer만 없으면 작은 화면에서도 문제없이 보이게 될거라 추후 footer가 개편되면 알아서 해결될 문제같다고 생각해요.
> Feat: 타이머, 스코어 위치 및 애니메이션 교체

- public/locale/en/ranking.json
- public/locale/ko/ranking.json
- src/components/DropDown/DropDown.tsx
- src/pages/games/SnackGame/ranking/RankingPage.tsx
- src/pages/games/SnackGame/ranking/components/RankingSection.tsx
- 리팩토링
- #226
- `totalRanking`이 빈 배열일 때 보여줄 `EmptyRanking`을 만들었습니다
- 이거 스낵이가 트로피를 잡고있는 이미지를 넣고 싶어서 일단 TODO로 이미지 교체 주석을 달아두긴 했는데요................
씁......... 지피티가 못 만들어 낼까요....?
💥이미지가 예전 main.png (과자봉지) 로 뜨긴 하는데 제가 #225 에서 main.png를 스낵이로 바꿔놨어요!
> Refactor: 시즌에 등록된 랭킹이 없을 때 빈 페이지 처리

- src/App.tsx
- src/api/apple-game.api.ts
- src/components/Error/RetryError.tsx
- src/components/base/ErrorBoundary.tsx
- src/hooks/queries/appleGame.query.ts
- src/pages/error/ErrorPage.tsx
- src/pages/games/SnackGame/game/SnackGameBase.tsx
- src/pages/games/SnackGame/game/SnackGamePage.tsx
- src/pages/games/SnackGame/game/game.type.ts
- src/pages/games/SnackGame/game/legacy/legacyType.ts
- src/pages/games/SnackGame/game/legacy/view/appleGame/DefaultMode.tsx
- src/pages/games/SnackGame/game/popup/PausePopup.ts
- src/pages/games/SnackGame/game/popup/PausePopup.tsx
- src/pages/games/SnackGame/game/popup/SettingPopup.ts
- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/game/screen/LobbyScreen.ts
- src/pages/games/SnackGame/game/screen/ResultScreen.ts
- src/pages/games/SnackGame/game/util/api.ts
- src/pages/games/SnackGame/ranking/RankingPage.tsx
- src/utils/atoms/common.atom.ts
- src/utils/types/common.type.ts
- 신규 피처
- #231 
기존에 message만 노출하던 RetryError, ErrorPage를 수정해 error code도 보여줄 수 있도록 변경했습니다.
```typescript
export interface FallbackProps {
error?: Error & { code?: string };
resetErrorBoundary?: () => void;
message?: string;
}
```
RankingPage에 QueryBoundary가 누락된걸로 보여 컴포넌트 단위의 핸들링을 위해 QueryBoundary를 추가했습니다.
Pixi 의 경우 React 환경 바깥에서 동작하는 객체이기 때문에 내부에서 발생한 오류가 Errorboundary로 전파되지 않습니다.
이를 해결하기 위해 이벤트 기반 통신을 지원하는 Pixi의 EventEmitter 객체를 사용했습니다.
아래는 SnackGame 에러 핸들링을 도식화 한 그림입니다.
EventEmitter의 이벤트는 SnackGameBase 렌더링 시 useEffect에 의해 등록되고 해제됩니다.
Pixi에서는 기본적으로 try - catch를 사용해 비동기 작업의 에러를 잡고 EventEmitter의 emit 메서드를 통해 error 객체를 전달해 이벤트를 트리거 합니다.
Emitter에 등록된 handler 함수가 useError의 setError 함수를 호출하고 useErrror의 useEffect 내부에서 error를 throw합니다.
useEffect 내부에서 Error를 throw 하기에 React 라이프 사이클 내에서 발생한 오류로 …
> Feat: SnackGame API 연동 및 에러 핸들링 개선

- src/pages/GameLayout.tsx
- src/pages/user/setting/SettingPage.tsx
- 이슈대응
- #245
- 웹뷰로 스낵게임에 접근할 경우 전역상태를 업데이트 하는 코드를 `GameLayout`에 추가했습니다
@0chil
[웹뷰 문서](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#useragent) 보니까 `WebView` 쓸 때 userAgent 설정이 가능하던데, 
기존 userAgent 뒤에 적당한 문자열 하나 붙여서 보내주실 수 있을까요? (일단은 'RN'으로 해둔 상태)
모바일 웹과 웹뷰를 구분하려면 이 과정이 필요할 거 같습니다!!
> fix: webview로 접근할 경우 `GameLayout`에서 프로필 요청을 보낸다

- src/pages/games/SnackGame/game/SnackGameBase.tsx
- src/pages/games/SnackGame/game/SnackGamePage.tsx
- src/pages/games/SnackGame/game/hook/initializeApplication.tsx
- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/game/screen/SnackgameApplication.ts
- resolves: #250 
- 앱 백그라운드 시 게임 및 bgm을 일시정지합니다.
- 지난 PR에서 발생한 오류도 고쳤습니다!
- 앱 복귀 시 bgm을 다시 재생합니다.
- 스낵게임 페이지 접근 시 불필요하게 실행되는 예외 핸들러를 개선하였습니다.
- `SnackgameApplication.onPause()` -> `SnackgameApplication.onLostFocus()`/`onGotFocus()`로 변경하였습니다.
- 헷갈리지 않도록 `AppScreen.onPause()`/`onResume()`과 의미를 구분하였습니다.
이번 PR이 찐찐막입니다 ㅠㅠ
> fix: 앱 백그라운드시 게임을 일시정지한다

- src/pages/games/SnackGame/game/hook/initializeApplication.tsx
- resolves: #256 
탭을 벗어나면 게임이 일시정지됩니다.
이슈에서 언급한대로 [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)를 사용했습니다.
오랜만에 생각한대로 쉽게 되는군요 ㄷㄷ 👍
> feat(SnackGame): 브라우저 포커스를 잃으면 게임을 일시정지한다

- src/components/BottomNav/BottomNav.tsx
- src/constants/loadImage.ts
- src/pages/auth/AuthPage.tsx
- src/pages/games/SnackGame/game/SnackGameBase.tsx
- src/pages/games/SnackGame/game/game.type.ts
- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/game/screen/SnackgameApplication.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameAction.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameBoard.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameStats.ts
- src/pages/games/SnackGame/game/ui/BeforeGameStart.ts
- src/pages/games/SnackGame/game/ui/GameEffect.ts
- src/pages/games/SnackGame/game/ui/Score.ts
- src/pages/games/SnackGame/game/ui/Waves.ts
- src/pages/games/SnackGame/game/util/api.ts
- src/pages/games/SnackGame/ranking/RankingPage.tsx
- src/pages/games/SnackGame/ranking/components/RankingSection.tsx
- src/pages/games/SnackGame/ranking/components/UserRanking.tsx
- 리팩토링
- #254 
- `UserRanking` 위치를 `DropDown` 아래로 이동
- `BottomNav`의 position을 sticky로 수정
= 랭킹 최하단까지 보이게 하기 위함
| before | after |
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/3e0faecf-64be-4aa1-b09e-05d1e0f69e8c)|![image](https://github.com/user-attachments/assets/911a0930-b879-4f97-a33b-bdcb538b10e7)|
(그리고 아주아주 사소한 오타 수정과 console.log 2개 제거)
- File Change에서 한번에 보는 것보다 커밋 하나씩 넘기면서 보는 게 편할 거 같아요!
- Tab, DropDown을 합성 컴포넌트 패턴으로 개선하는 작업을 여기서 할까 했는데,
그러면 보기가 너무 불편할 거 같아 별도 이슈로 진행하겠습니다......! 넘 늦어졌군요 🥺
> refactor: 랭킹 페이지 UI, BottomNav 수정

- src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
- src/pages/games/SnackGame/game/legacy/view/appleGame/ClassicMode.tsx
- src/pages/games/SnackGame/game/legacy/view/snackGame/NewSnackGameMod.tsx
- src/pages/games/SnackGame/game/legacy/view/snackGame/SnackGameMode.tsx
- 이슈 대응
- #258
상위 0% 일 때도 문구가 정상적으로 보이도록 코드를 수정했습니다
(사진은 **`percentile` 변수에 고의로 0 넣어서** 테스트한 거고, 34점일 때 상위 0% 아닙니다! 혹시 수상하게 생각하실까봐)
아래는 구구절절 히스토리인데요 사실 굳이 안 읽으셔도 되긴 합니다 
1. 왜 `percentile = 0`일 때 0만 보였냐!
```tsx
{percentile && <p>전체 사용자 중 상위 {percentile}%의 점수에요!</p>}
```
- and 연산자는 처음으로 만나는 falsy 값을 반환함 (0은 falsy)
- 따라서 주어진 상황에서 표현식은 아래처럼 바뀜<br/><br/>
```tsx
{percentile} //  percentile 값 = 0만 출력하게 됨
```
2. and 연산자는 왜 썼냐
```tsx
interface GameResultProps {
score: number;
percentile?: number; // percentile이 선택 속성이라, undefined일 수 있기 때문에 and 연산자가 필요했음
reStart: () => void;
}
```
3. 왜 선택 속성으로 만들었냐
레거시 코드의 변경 사항에서 눈치 채셨겠지만?
예전에는 게임 종료 API 연결 전이어서 넘길 `percentile` 값이 없었음 = percentile을 잠시 선택 속성으로...
근데 서버에서는 percentile 값을 항상 주는데, 레거시 코드를 위해 선택 속성으로 해둔다면
나중에 헷갈릴 수 있을 거 같아 필수 속성으로 바꿨습니당
> fix: `GameResultProps`의 percentile을 필수 속성으로 변경

- src/components/BottomNav/BottomNav.tsx
- src/components/DropDown/DropDown.tsx
- src/components/Header/Header.tsx
- src/components/Modal/Modal.tsx
- src/components/SnackRain/SnackRainContainer.tsx
- src/components/TopBar/TopBar.tsx
- src/pages/user/components/ExpChart.tsx
- src/pages/user/components/UserInfo.tsx
- tailwind.config.js
- 리팩토링 & 이슈 대응
- #257 
- bottom nav보다 modal이 더 위에 뜨도록 z-index를 수정했습니다
- 관리하기 편하게 z-index를 tailwind.config 파일에 커스터마이징 해서 사용하는 방식으로 수정했습니다
- 굳이 z-index를 쓰지 않아도 되는데 쓰는 부분 수정
- `-1`, `1` 쓰다가 갑자기 `999`로 급발진 하는 이유
작은 숫자는 주변 요소와의 z-index만 조절하면 되는 경우!
근데 BottomNav, Modal 같이 여러 곳에서 쓰일 수 있는 컴포넌트는 아예 크게 해두는게
나중에 z-index 가진 요소를 추가하기 편할 거 같다는 띵킹
> refactor: z-index를 tailwind.config 파일에서 관리하도록 수정

- src/api/index.ts
서비스 사용중 토큰 만료 + 재발급이 발생한 경우를 대응합니다.
현재 웹에서는 interceptor를 통해 재발급하고 있는데요, 덕분에 앱의 WebView에서도 1주일 이상 로그인이 잘 유지됩니다.
그러나 앱 재실행 시 문제가 생기는데요.
앱 입장에서는 WebView 내부적으로 바뀐 쿠키를 알 수있는 방법이 마땅치 않습니다.
그래서 오랜만에 앱을 재실행하면 로그인이 풀립니다.
이에 이벤트 기반으로 interceptor의 동작을 일부 위임하고자 합니다.
- 앱에 토큰 재발급을 요청하고, 앱의 토큰 재발급 + 쿠키 삽입 처리가 완료되면 원본 요청을 다시 시도합니다.
- 앱의 재발급 처리를 기다리는 최대 시간은 5초입니다.
- 앱이 시간 안에 처리하지 못하면 웹이 로그아웃되고, 이어서 앱도 로그아웃됩니다.
이번 변경의 영향을 받지 않고, 기존과 동일합니다.
점점 스낵게임 전용 브라우저 만들기가 되어가네요 ㅋㅋ
하지만 앱과 웹을 동시에 운영하기는 쉽지 않기 때문에,,, 이게 맞다고 생각합니다.
> feat: 앱에 토큰 재발급을 위임할 수 있다

- src/components/BottomNav/BottomNav.tsx
- src/pages/games/SnackGame/ranking/components/RankingSection.tsx
- resolves: #266 
BottomNav가 스크롤과 함께 오르락 내리락하는 문제를 해결합니다.
BottomNav의 position을 fixed로 복구하고, 랭킹 페이지 하단에 BottomNav 높이만큼(`mb-16`, `4rem`) 마진을 주었습니다.
일단은 임시방편.. 레이아웃 재구성을 고민해봐야할 것 같기도 합니다.
> fix(BottomNav): BottomNav가 스크롤되는 문제

- src/pages/games/SnackGame/ranking/components/RankingSection.tsx
- 이슈 대응
- #268
- 게스트 유저일 때 `UserRanking` 컴포넌트를 렌더링 하지 않기 때문에,
`DropDown`과 `TopRanking` 사이 여백 보장을 위해 `Spacing` 컴포넌트를 삽입했습니다
> fix: 게스트의 랭킹 페이지가 잘못 그려지는 문제

- src/components/Auth/OAuth.tsx
- src/hooks/queries/members.query.ts
- 이슈 대응
- #273
- 프로필 쿼리 무효화의 위치를 이동시켰습니다
- 이전: `useIntegrateMember` 훅에 있던 `onSettled` (mutation이 성공하면 수행됨)
- 현재: `OAuth`의 `onOAuthSuccessHandler`
- 사유: 앱/웹에서 모두 통합 결과를 바로 보여주기 위해 프로필 쿼리 무효화가 필요한 상황
그러나 해당 코드가 `onSettled`에 위치할 경우 앱에서 수행할 수 없음
앱에서는 mutationFn(**membersApi.integrateMember**)를 수행하면 안되기 때문임
생각해보니 `OAuth`의 `onOAuthOnSuccess` prop 타입이 `() => Promise<MemberType>` 라서,
처음 제안했던 방식은 관련 코드 주르륵 수정해야한다는 점에서 적절하지 못했던 거 같아요  ╯︿╰
(무효화는 리턴 타입이 `Promise<void>`임)
~~역시 사람이 문제다~~
> fix: `OAuth`의 `onOAuthSuccessHandler`에 프로필 쿼리 무효화 추가

- src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
`GameResult` 창에서 소셜 로그인을 할 때, 앱에서는 integrateMember를 호출하지 않게 했습니다.
변경사항 공유를 하나 깜빡했네요.
OIDC를 사용하면 기존처럼 소셜 로그인을 1. OAuth 과정, 2. 서비스 로그인으로 분리할 필요가 없습니다.
이 점을 활용해 OIDC 로그인 시 게스트 계정을 새 계정으로 자동 통합하도록 로직을 작성했는데요.
- https://github.com/snack-game/server/pull/158
웹도 OIDC 기반으로 옮겨가면서 이걸 활용해 회원가입/전환 로직 부담을 좀 덜어내면 어떨까요?
> fix(GameResult): 앱은 사용자 통합 API를 호출하지 않는다

- src/pages/games/SnackGame/game/SnackGameBase.tsx
- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/ranking/components/UserRanking.tsx
이 화면에 문제가 2가지 있는데요.
하나는 자신의 랭킹이 있음에도 (6위, 39점) 표시되지 않는다는 것.
하나는 아직 랭킹이 없는 상황에서 1등이 너무 높이 있다는 것입니다.
- 게임 종료 시 query를 invalidate하게 변경했습니다. 
이 상태에서 랭킹 페이지 접근 시 자신의 랭킹을 새로 받아오게 됩니다.
- 자신의 랭킹이 아직 없는 경우 공백을 표시합니다. (`<Spacing size={5} />`)
Q. 쿼리 invalidation을 이렇게 직접 다뤄줘야 할까요? 아직 '쿼리'로 묶이지 않아서 불편한거겠죠?
> fix(SnackgameBase): 게임 종료 시 자신의 랭킹을 새로 받아와야 한다

- src/api/groups.api.ts
- src/constants/regexp.constant.ts
- src/hooks/queries/members.query.ts
- src/hooks/useInput.ts
- src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
- src/pages/user/components/ProfileSection.tsx
- src/pages/user/components/UserInfo.tsx
- 이슈대응
- #288
1. 그룹이 없는 경우 서버 응답의 `group` = null ➡️ 이는 `newGroup.value = ''`으로 초기화
2. 공백은 `GROUP_CHANGE_REGEXP` 정규식에 어긋나 invalid한 값으로 판단
1. 그룹이 공백인 경우 정규식을 거치지 않고 valid한 값으로 판단하도록 합니다
> 💫 닉네임만 바꿨을 때 프로필 수정이 가능한 점 -> 이후 그룹 설정도 되는 점에 집중해서 봐주시면 됩니다!!
해당 부분에 코멘트로 서술했습니다!
해당 부분에 코멘트로 서술했습니다!!
그근데
한번 그룹에 가입하면 탈퇴는 안되는 거네요...?!
나중에 그룹 이름을 공백으로 보내면 탈퇴 처리한다 ⬅️ 요런 기능도 계획에 있나요??
> fix: 그룹이 없는 경우 프로필 수정이 불가한 문제

- package.json
- pnpm-lock.yaml
- src/pages/user/components/ProfileSection.tsx
- src/utils/heicConverter.ts
[HEIF](https://ko.wikipedia.org/wiki/%EA%B3%A0%ED%9A%A8%EC%9C%A8_%EC%9D%B4%EB%AF%B8%EC%A7%80_%ED%8C%8C%EC%9D%BC_%ED%8F%AC%EB%A7%B7)는 '고효율' 이미지 파일 포맷입니다. (라고 주장하네요)
애플 생태계에서는 이 포맷을 `.heic`로 활용하곤 하는데, 일반적인 이미지가 아니라서 애플 생태계에서만 렌더링이 가능하다는 문제가 있습니다.
때문에 스낵게임 프로필 이미지 변경에서도 동일한 문제가 발생하고 있습니다.
이걸 해결하기 위해서 생각해본 조치가 있는데요,
1. 서버에서 이미지를 변환하여 저장
2. 클라이언트에서 이미지를 변환하여 업로드
최종적으로는 2를 선택한 상황입니다. [(heic2any 사용)](https://alexcorvi.github.io/heic2any/#options)
최대한 1로 해보려고 했으나, Java 진영에는 적절한 라이브러리가 없더라구요... ㅠㅠ
그렇다고 제가 만들기엔 지식과 시간이 아까웠어요.
그래서 일단 서버에서는 HEIC 그대로 업로드 할 수 있도록 조치한 상태입니다. (애플 기기끼리만 볼 수 있음)
여기에 클라이언트 사이드 변환이 추가되면 왠만해서는 이미지가 안보이거나, 업로드 불가한 일은 없을 것 같네요.
프로필 이미지 선택 시 파일 타입이 `image/heic`라면, jpeg로 변환합니다.
이 때, 이미지 로드 최적화를 위해 1MB 이내로 다운스케일링도 함께 진행합니다.
> feat(ProfileSection): HEIC 이미지를 변환하여 업로드한다

- src/pages/games/SnackGame/game/screen/GameScreen.ts
- 소공전을 위해 임의 수정했던 시간!!! 다시 돌려놓기
- 저번에 30초로 수정해놨던 커밋 revert 했읍니다 (빌드 테스트 끗나면 바로 머지할게용)
> chore: 게임 시간 30초 -> 120초로 돌려놓기

- src/pages/user/components/ProfileSection.tsx
- 이슈 대응
- #294 
- 이름/그룹/이미지 순으로 수정 요청 보내던 순서를 수정 (이미지/이름/그룹)
- 그룹 가입이 안된 상태에서 && 그룹 수정이 없을 경우 `return undefined` ➡ `return newProfile`로 수정
- 이미지 수정이 안됐던 이유
- 문제가 발생하던 상황 (그룹 없고 그룹 수정도 없음)
- `return;` 을 넣어둔 탓에
- 그룹 수정 아래 있던 이미지 수정 조건문은 알 바 아니고.... 함수를 바로 탈출.... 해버림
땡스투 손모양...........
그리고 그룹 없을 때 안된다고 발견해준 땡칠에게 박수. 보냅니다
이미지 압축 및 변환 (heif) 작업은 별도의 브랜치에서 진행할게요~~~! 까먹은 거 아님
> fix: 그룹이 없으면 이미지 수정이 안되는 문제

- src/components/Auth/OAuth.tsx
- src/components/Modal/Modal.tsx
- src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
- 이슈 대응
- #296 
- `Modal`의 높이가 부족해서 생기는 문제여서 `h-1/2`를 `min-h-[50%]`로 수정했습니다
- 전: 높이 50vh 고정
- 후: 높이 **최소** 50vh & 콘텐츠에 따라 더 늘어날 수 있음
- 단, `height`를 `min-height`로 바꿀 경우 자식 요소의 `height: 100%`이 동작하지 않게 됩니다
`height: 100%`을 사용하지 않고도 남은 높이 전부를 차지할 수 있게 `flex-grow`로 수정했어욥
주말 중에 안드로이드 테스트 쪼끔 더 해봤는데, 안드 자체의 문제는 더 발견 못해서
일단 심사 한번 제출해도 될 거 같습니다............!!
> fix: Modal 높이가 콘텐츠가 비해 짧은 문제

- src/pages/games/SnackGame/game/SnackGameBase.tsx
- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/game/screen/SnackgameApplication.ts
- src/pages/games/SnackGame/game/ui/GameEffect.ts
- resolves: #280
이 이슈는 해결이 어려워 보이던 이슈였는데요.
조사해보니 생각보다 너무나 간단한 문제여서 당황스럽습니다 😅
게임을 재시작하면 화면 전환 과정에서 스낵 제거 애니메이션이 발생합니다.
이 애니메이션의 종료를 기다리지 않고 새 게임을 시작해버렸기 때문에 발생한 문제였습니다.
<details>
<summary>상황을 자세히 말씀드려보자면... 더보기</summary>
`src/pages/games/SnackGame/game/util/pool.ts`에 MultiPool 객체가 있는데요,
스낵게임에서는 이 친구를 활용, 게임에 필요한 스낵 객체를 재사용하고 있습니다.
따라서 스낵 제거 애니메이션이 진행되고 있다면, 새 게임에서도 해당 스낵 객체를 재사용하기 때문에
게임이 시작된 상태로 스낵 제거가 이어지게 됩니다 🥲
</details>
화면 전환 시 스낵 제거 애니메이션을 기다리도록 하여 문제를 해결했습니다
- https://github.com/snack-game/front/pull/285#discussion_r1711536550 에서 다뤘던 문제입니다
`SnackGameBase.navigateToLobby`에서 `dismissPopup()`을 직접 수행하고 있었는데, 이를 스낵게임 어플리케이션 안으로 집어넣었습니다.
이제 화면 전환 시 팝업을 신경쓰지 않아도 됩니다 :)
> fix(GameEffect): 게임 재시작 시 스낵이 사라지는 문제를 해소한다

- src/pages/games/SnackGame/game/popup/PausePopup.ts
- src/pages/games/SnackGame/game/popup/RulePopup.ts
- src/pages/games/SnackGame/game/popup/SettingPopup.ts
- 리팩토링하다가 만난 이슈 대응
- #302 
- `Popup` 클래스 안에 있는 함수들을 클래스 메서드 형식으로 통일
- `connect()` 인자로 전달되는 함수는 Popup 인스턴스와 바인딩 될 수 있게 수정
다음부턴 이런 앱 사용에 큰 방해가 되는 문제가 생기면 hotfix 브랜치 파서 처리할게요!!
급하다고 master에서 바로 revert 갈기지 않기....... 29483번 썼습니다 (마음으로)
> style: Popup 내부 함수 형식 통일 및 `connect()` 인자 수정

- src/App.tsx
- src/constants/path.constant.ts
- src/pages/games/SnackgameBiz/SnackGameBizBase.tsx
- src/pages/games/SnackgameBiz/SnackGameBizPage.tsx
- src/pages/games/SnackgameBiz/components/GameResult.tsx
- src/pages/games/SnackgameBiz/util/api.ts
- resolves: #304 
기존 스낵게임 페이지와 별도로 Snackgame Biz 페이지를 추가합니다.
- 게임은 우선 게스트로 진행됩니다.
- 게임 결과는 `postMessage`를 통해 제공됩니다. (추후 JWT 적용 예정)
- 랭킹 및 프로필 서비스는 (아직) 제공되지 않습니다.
자세한 사용 방법은 별도의 문서를 만들어 블로그를 통해 배포 예정입니다.
오늘 스낵게임 관련 미팅이 있어서 선 머지 후 리뷰를 반영하겠습니다!
양해 부탁드립니다 🙇🏻🙇🏻🙇🏻
> feat(games): 스낵게임 Biz 페이지 추가

- src/pages/games/SnackGame/game/SnackGameBase.tsx
- 이슈 대응
- #290 
- `handleNonLoggedInUser` 내에서 로컬 스토리지 값을 바로 읽도록 했습니다
(움짤이 좀 기네요 😅 아래 내용을 녹화했습니다)
(1) 로그아웃 상태에서 자동 게스트 로그인 성공
➡️ (2) 로그인 이후 해당 계정으로 게임 시작 성공
➡️ (3) 로그아웃 후 자동 게스트 로그인 성공
이슈 코멘트로 문제 상황과 수정 방향에 대한 내용 나누어서 바로 머지하겠습니다!
> fix: `handleNonLoggedInUser`에서 최신 `userInfo`를 반영하지 못하는 문제 수정

- src/pages/games/SnackGame/game/SnackGameBase.tsx
- src/pages/games/SnackGame/game/game.type.ts
- src/pages/games/SnackGame/game/screen/GameScreen.ts
- src/pages/games/SnackGame/game/snackGame/SnackGame.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameAction.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameBoard.ts
- src/pages/games/SnackGame/game/snackGame/SnackGameUtil.ts
- src/pages/games/SnackGame/game/util/api.ts
- src/pages/games/SnackgameBiz/SnackGameBizBase.tsx
- src/pages/games/SnackgameBiz/util/api.ts
- 신규 피쳐인 척 옛날 피쳐 살리기
- #307
- 게임판은 프론트에서 랜덤 생성한다
- 스트릭 제거 시 그 길이만큼 점수를 올리기 위해 점수 수정 API 요청을 보낸다
- 게임판은 서버에서 보내주는 값을 사용한다
- 스트릭 제거 시
- 일반 스트릭은 `cumulativeStreaks` 배열에 저장한다
- 황금 스트릭은 지금까지 제거한 모든 스트릭을 넣어서 검증 API 요청을 보낸다 (새 판을 받아와야 해서)<br/><br/>
> 일시정지와 게임 종료 시, 아직 검증되지 않은 스트릭이 있다면 검증 API 요청을 보낸 후 일시정지/종료합니다!
> 아래 항목을 확인할 수 있는 스크린샷입니덩
>
> - 황금 스낵이 없어질 때 `streaks` 요청을 보내는 점
> - 아직 검증되지 않은 스트릭이 있을 때 일시정지하면 검증 -> 일시정지 요청이 가는 점
어제까지 한다고 해놓고. 전 거짓말쟁이입니다.
> feat: 게임판 검증 API 적용

- src/pages/games/SnackgameBiz/SnackGameBizBase.tsx
- resolves: #309
오랜만의 PR입니다!
이걸 이제야 합니다 ㅎㅎㅎ
고객이 직접 구현할 수 있도록 게임 결과 팝업을 제거합니다.
추후 백오피스 구현된다면 껐다켰다 할 수 있으면 좋겠군요!
- 게임 결과 팝업 제거
> feat(SnackgameBiz): 게임 종료화면 제거

- src/components/BottomNav/BottomNav.tsx
- src/pages/games/SnackGame/game/util/hapticFeedback.ts
약한(light) 햅틱을 적용했습니다
약한(light) 햅틱을 적용했습니다
> feat: 하단 바에 햅틱 피드백을 적용한다

- public/locale/en/game.json
- public/locale/ko/game.json
- src/pages/games/SnackGame/game/legacy/components/GameResult.tsx
- src/pages/games/SnackGame/game/popup/SettingPopup.ts
- 이슈 대응
- #337 
- 텍스트가 팝업을 벗어나지 않게 문구를 간결하게 수정
- 게임 설정 내 미번역된 부분 수정
- 게임 결과 내 미번역된 부분 수정
- "변경없이 재심사" 넣으신 버전이 아마 통과된 걸로 보이는데 맞나요..? (지금 스토어에 올라간 1.2.1 (2) 버전)
- 제가 확인해보려고 Apple Developer 로그인 때렸다가, , , 맞다 내 번호가 아니지, , , 했습니다
인증번호 문자가 갔을텐데 제가 범인입니다
- 바로 머지하려다가 메일 상으로 가장 최근 상태가 `ready for distribution` 이길래 일단,, 냅두겠으빈다
> fix: 게임 내 번역 텍스트 수정

- src/App.tsx
- src/components/Auth/OAuth.tsx
- src/components/Header/Header.tsx
- src/constants/localStorage.constant.ts
- src/hooks/queries/auth.query.ts
- src/pages/user/setting/SettingPage.tsx
- src/pages/withdraw/WithdrawPage.tsx
- 버그 픽스
- #347 
- window.location으로 현재 url을 판단해서 'biz'가 포함되어 있으면 조기 종료
- 이외에는 기존 동작과 동일하게 updateProfile() 호출 ➡️ 에러 생기면 전역 상태 초기화 & 삭제
- 사용하지 않는 스토리지 값 관련 코드 제거 (LOCAL_STORAGE_KEY.USER_EXPIRE_TIME)
- 원래 App.tsx에서 쓰다가 주석 처리해놔서 사실 세팅/삭제만 하고 아무데서도 안 쓰고 있슴
> fix: Biz 환경에서 getMemberProfile 호출 방지

- src/pages/games/SnackGame/game/SnackGameBase.tsx
- #349 의 연장선. . . 
- 신규 피처
> 목록(targets)이 있는데 못 띄운건지 진짜 목록이 빈 배열인지 구분이 안 가서
- 를 구분하기 위해 targets이 빈 배열로 오는 경우는 센트리에 해당 세션 ID를 기록하려고 함
> feat: targets이 빈 배열이면 Sentry에 기록한다

- src/pages/main/components/HeroSection.tsx
- 이슈 대응
- #355 
- `<HeroSection>` `py-12`를 `pt-16` & `pb-12`로 분리
- 위쪽 패딩(12)이 헤더 높이(16)보다 작아서 확대 시 헤더가 컨텐츠를 약간. 가렸음
- 아래쪽 패딩은 12로 유지
| 전 | 후 |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/1e590b41-96bc-4a4b-b7ef-4e21d076bcee) | ![image](https://github.com/user-attachments/assets/8b53f0ba-bea7-4907-9f26-cdc8570ed1e6) |
- 이 상황에서 헤더 - 콘텐츠 사이 여백을 위해 흰색 영역에 `pt-4` 추가
- 150%~ 배율부터는 h-screen 포기
> fix: 랜딩 페이지 확대 시 UI 깨짐

- src/constants/localStorage.constant.ts
- src/pages/games/SnackGame/game/SnackGamePage.tsx
- src/pages/games/SnackGame/game/hook/useNoticeModal.tsx
- 신규 피처
- #352 
- (주로) 공지사항 노출용 일회성 모달 구현
- useNoticeModal = openModal 호출 전에 날짜 처리만 추가된 훅입니다
- localStorage에 최근 공지 ID & 날짜를 저장해서 비교합니다
- 만약 공지 ID가 바뀌거나
- (공지 ID는 그대로지만) hideUntil 시각이 지나지 않았다면 모달을 노출하지 않습니다
- 공지 모달을 연달아 여러 개 띄울 상황은 아직 없어서 일단 하나만 뜬다고 가정하고 구현
(공지 내용은 `<Notice>`에 들어감 ➡️ 공지 바뀔 때마다 수정)
> feat: 일회성 모달 구현

- src/hooks/queries/notice.query.ts
- src/pages/games/SnackGame/ranking/components/NoticeSection.tsx
- 이슈 대응
- #375 
- 공지 데이터 (xml) 을 파싱할 때 날짜 (`<pubDate>`) 기준으로 정렬합니다
> fix: 랭킹 페이지에서 과거 공지가 보이는 문제
